name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ProductService.API

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./ProductService.API

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./ProductService.Tests